eckerdproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/', include('portal.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.urls import path
from . import views

app_name = 'portal'

urlpatterns = [
    # /portal/
    path('', views.IndexView.as_view(), name='index'),

    # /portal/login/
    path('login/', views.LoginView.as_view(), name='login'),

    # /portal/article/add/
    path('article/add/', views.ArticleCreate.as_view(), name='article-add'),

    # /portal/article/<pk>/
    path('article/<int:pk>/', views.ArticleUpdate.as_view(), name='article-update'),

    # /portal/article/<pk>/delete/
    path('article/<int:pk>/delete/', views.ArticleDelete.as_view(), name='article-delete'),
]

portal/models.py
from django.db import models
from multiselectfield import MultiSelectField



class Class(models.Model):
    DAYS_OF_WEEK = (
        (0, 'Sunday'),
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
    )

    name = models.CharField(max_length=250)
    code = models.CharField(max_length=15)
    teacher = models.CharField(max_length=100,)
    days = MultiSelectField(choices=DAYS_OF_WEEK, max_choices=7)
    start = models.TimeField(max_length=5, default='00:00')
    end = models.TimeField(max_length=5, default='24:00')
    description = models.TextField(max_length=2000)


class Article(models.Model):
    ARTICLE_TYPE = (
        ('news_article', 'News Article'),
        ('announcement', 'Announcement')
    )
    article_type = models.CharField(max_length=40, choices=ARTICLE_TYPE)
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    url = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})


# class Calendar(models.Model):
#
#
#
#
# class Week(models.Model):
#
#
#
# class Day(models.Model):
#
#
#
# class Event(models.Model):
#     name = models.CharField(max_length=100)
#     location = models.CharField(max_length=300, required=False)
#     all_day = models.BooleanField(default=False)
#     if all_day:
#         start = '00:00'
#         end = '24:00'
#     else:
#         start = models.TimeField(max_length=5, default='00:00')
#         end = models.TimeField(max_length=5, default='24:00')

portal/forms.py
from django.contrib.auth.models import User
from .models import Article
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


# class NewsForm(forms.ModelForm):
#
#     class Meta:
#         model = Article
#         fields = ['article_type', 'title', 'author', 'description', 'url']

portal/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View
from django.views import generic
from .forms import UserForm
from .models import Article, Class


class IndexView(generic.ListView):
    template_name = 'portal/index.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.all()


class ArticleCreate(CreateView):
    model = Article
    fields = ['article_type', 'title', 'author', 'description', 'url']
    success_url = reverse_lazy('portal:index')


class ArticleUpdate(UpdateView):
    model = Article
    fields = ['article_type', 'title', 'author', 'description', 'url']
    success_url = reverse_lazy('portal:index')


class ArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('portal:index')


class LoginView(View):
    form_class = UserForm
    template_name = 'portal/login_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(None)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            # correct username and password login the user
            login(request, user)
            return redirect('portal:index')

        return render(request, self.template_name, {'form': form})

portal/templates/portal/article_form.html
{% extends 'portal/base.html' %}

{% block title %}News Form{% endblock %}

{% block body %}

<div class="container-fluid" style="border: 2px solid black">
    <h3>Log In</h3>
    <form class="" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'portal/form_template.html' %}
        <div>
            <button type="submit" class="">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

portal/templates/portal/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'portal/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
    <nav>
        <h3>Navbar</h3>
    </nav>
</div>
    <main>
        {% block body %}
        {% endblock %}
    </main>
</body>
</html>

portal/templates/portal/form_template.html
{% for field in form %}
    <div class="">
        <div>
            <span class="">{{ field.errors }}</span>
        </div>
        <label class="">{{ field.label_tag }}</label>
        <div class="">{{ field }}</div>
    </div>
{% endfor %}

portal/templates/portal/index.html
{% extends 'portal/base.html'%}

{% block title %}<title>Home</title>{% endblock %}

{% block body %}
    <div>
        <div>
            <h1>Calender</h1>
        </div>
        <div id="calendar">
            <p>info</p>
        </div>
        {% include 'portal/calender_template.html' %}
    </div>
    <div id="news">
        <div>
            <h2>News</h2>
            {% for article in articles %}
                {% csrf_token %}
                <div>
                    <h3>{{ article.title }}</h3>
                    <h4>{{ article.author }}</h4>
                    <p>{{ article.description }}</p>
                    <p><a href="{{ article.url }}">Click here to read more...</a></p>
                    <form action="{% url 'portal:article-delete' article.id %}" method="post" style="display: inline-block">
                        {% csrf_token %}
                        <input type="hidden" name="article_id" value="{{ article.id }}">
                        <button type="submit">
                            <span>Delete</span>
                        </button>

                    </form>
                </div><br>
            {% endfor %}
        </div>
    </div>
{% endblock %}

portal/templates/portal/login_form.html
{% block body %}

<div class="container-fluid" style="border: 2px solid black">
    <h3>Log In</h3>
    <form class="" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'portal/form_template.html' %}
        <div>
            <button type="submit" class="">Submit</button>
        </div>
    </form>
</div>

{% endblock %}